---
 - name: Install Code Development
   hosts: "*"
   become: true
   tasks: 

    - name: Ansible apt-get to get install build-essential
      apt:
        name: build-essential
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install cmake
      apt:
        name: cmake
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install doxygen
      apt:
        name: doxygen
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install graphviz
      apt:
        name: graphviz
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install libncurses-dev
      apt:
        name: libncurses-dev
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install gawk
      apt:
        name: gawk
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install flex
      apt:
        name: flex
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install bison
      apt:
        name: bison
        state: present
        force_apt_get: yes 

    - name: Ansible apt-get to get install openssl
      apt:
        name: openssl
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install libssl-dev
      apt:
        name: libssl-dev
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install dkms
      apt:
        name: dkms
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install libelf-dev
      apt:
        name: libelf-dev
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install libudev-dev
      apt:
        name: libudev-dev
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install libpci-dev
      apt:
        name: libpci-dev
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install libiberty-dev
      apt:
        name: libiberty-dev
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install autoconf
      apt:
        name: autoconf
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install llvm
      apt:
        name: llvm
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install nodejs
      apt:
        name: nodejs
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install pkg-config
      apt:
        name: pkg-config
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install automake
      apt:
        name: automake
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install libtool
      apt:
        name: libtool
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install make
      apt:
        name: make
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install libboost-all-dev
      apt:
        name: libboost-all-dev
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install squashfs-tools
      apt:
        name: squashfs-tools
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install python-pip
      apt:
        name: python-pip
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install multistrap
      apt:
        name: multistrap
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install qemu-user-static
      apt:
        name: qemu-user-static
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install hashdeep
      apt:
        name: hashdeep
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install parted
      apt:
        name: parted
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install kpartx
      apt:
        name: kpartx
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install dosfstools
      apt:
        name: dosfstools
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install squashfuse
      apt:
        name: squashfuse
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install wget
      apt:
        name: wget
        state: present
        force_apt_get: yes

    - name: Ansible apt-get to get install curl
      apt:
        name: curl
        state: present
        force_apt_get: yes

